### ISSUE TITLE
Output scale/range

### ISSUE THREAD

**Issue by 123aaron** [almarklein/pyelastix#6]
Hi,

Thanks for putting the wrapper together, it works well.

However, I am having a issue with the output data. My input images/arrays are both converted to 8bit (0-255), but the output is gives values in the range of around (-0.019... - 0.099...). is there a reason why the scales are so different on the output? Can the wrapper be coerced into matching the output scale to the input?
My aim is to not lose the initial values of the moving image such that I can convert back to the prior values from the 8bit conversion.

Thanks.

**Comment by soupault** [comment]
I believe the scaling issue is due to this line - https://github.com/almarklein/pyelastix/blob/master/pyelastix.py#L562.

As for data types, see parameters `FixedInternalImagePixelType`, `MovingInternalImagePixelType`, `ResultImagePixelType` in http://elastix.isi.uu.nl/doxygen/index.html. In general, I recommend to work with images in float.

**Comment by soupault** [comment]
Fixed in #20, the current redaction should not change the intensity range.

I am going to add more tests concerning this later.
